changes

diff --git a/.github/workflows/Tests.yml b/.github/workflows/Tests.yml
--- a/.github/workflows/Tests.yml
+++ b/.github/workflows/Tests.yml
@@ -75,37 +75,47 @@ jobs:
           
       - name: Convert JTL to JUnit XML
         run: |
-            FILENAME=$(basename $(ls src/test/jmeter/*.jmx | head -n 1) .jmx)
-            echo "Nom detecte pour Octane : $FILENAME"
-            
-            # ATTENTION: Pas de guillemets autour de EOF ici !
-            cat << EOF > jmeter-results-to-junit.xsl
-            <?xml version="1.0" encoding="UTF-8"?>
-            <xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
-              <xsl:output method="xml" indent="yes" encoding="UTF-8"/>
-              <xsl:template match="/testResults">
-                <testsuites>
-                  <testsuite>
-                    <xsl:for-each select="*">
-                      <testcase>
-                        <xsl:attribute name="classname"><xsl:value-of select="name()"/></xsl:attribute>
-                        <xsl:attribute name="name">$FILENAME</xsl:attribute>
-                        <xsl:attribute name="time"><xsl:value-of select="@lt div 1000"/></xsl:attribute>
-                        <xsl:if test="assertionResult/failureMessage">
-                          <failure><xsl:value-of select="assertionResult/failureMessage"/></failure>
-                        </xsl:if>
-                        <xsl:if test="@s = 'false'">
-                          <error>La requete a echoue (voir les logs JMeter)</error>
-                        </xsl:if>
-                      </testcase>
-                    </xsl:for-each>
-                  </testsuite>
-                </testsuites>
-              </xsl:template>
-            </xsl:stylesheet>
-            EOF
-            
-            xsltproc jmeter-results-to-junit.xsl results.jtl > junit-report.xml
+          # 1. On récupère dynamiquement le nom du premier test JMX
+          FILENAME=$(basename $(ls src/test/jmeter/*.jmx | head -n 1) .jmx)
+          echo "Nom detecte : $FILENAME"
+          
+          # 2. On définit le fichier JTL source (celui généré par l'étape précédente)
+          # Si vous utilisez ma boucle 'for', le fichier s'appelle results_$FILENAME.jtl
+          JTL_FILE="results_${FILENAME}.jtl"
+          
+          # Vérification si le fichier existe pour éviter l'erreur "failed to load"
+          if [ ! -f "$JTL_FILE" ]; then
+            echo "ERREUR : Le fichier $JTL_FILE n'existe pas. Vérifiez l'étape de Run."
+            exit 1
+          fi
+
+          # 3. Création du template XSL
+          cat << 'EOF' > jmeter-results-to-junit.xsl
+          <?xml version="1.0" encoding="UTF-8"?>
+          <xsl:stylesheet xmlns:xsl="http://w3.org" version="1.0">
+            <xsl:output method="xml" indent="yes" encoding="UTF-8"/>
+            <xsl:template match="/testResults">
+              <testsuites>
+                <testsuite name="JMeterTests">
+                  <xsl:for-each select="*">
+                    <testcase>
+                      <xsl:attribute name="classname">JMeter.<xsl:value-of select="@lb"/></xsl:attribute>
+                      <xsl:attribute name="name"><xsl:value-of select="@lb"/></xsl:attribute>
+                      <xsl:attribute name="time"><xsl:value-of select="@t div 1000"/></xsl:attribute>
+                      <xsl:if test="@s = 'false'">
+                        <failure>La requete a echoue (Status code <xsl:value-of select="@rc"/>)</failure>
+                      </xsl:if>
+                    </testcase>
+                  </xsl:for-each>
+                </testsuite>
+              </testsuites>
+            </xsl:template>
+          </xsl:stylesheet>
+          EOF
+          
+          # 4. Conversion avec le bon nom de fichier
+          xsltproc jmeter-results-to-junit.xsl "$JTL_FILE" > junit-report.xml
+
           
       - name: Upload JUnit Performance Report
         uses: actions/upload-artifact@v4
